### ISSUE TITLE
iOS 16.1 SDKS for GitHub Actions (Errors/Issues/Sysroot)

### ISSUE THREAD

**Issue by arichornlover** [xybp888/iOS-SDKs#7]
This is the weirdest thing I gotten. I tried any other sdks like 15.5 and never gotten an issue showing SYSROOT before
and here is the code, tried to resolve it in main.yml file.
`set sysroot ./System/Library/Frameworks/UIKit.framework`

**Comment by xybp888** [comment]
sdks does not have any executable files and will not ask you for any settings, please check your own environment configuration

**Comment by arichornlover** [comment]
Oh alright

**Comment by arichornlover** [comment]
I figured out the issue, the Makefile was using an way older version of iOS, now I see why the SDK wasn’t working

**Comment by arichornlover** [comment]
https://github.com/arichorn/uYouPlusExtra/actions/runs/3381016387/jobs/5614445867 Changes title due to the recent commit 5 hours ago. This was a random app I built with this SDK, right now I currently use 15.5 SDK to build it with no errors unlike this action

**Comment by arichornlover** [comment]
Most of the errors in this action is likely caused by the 16.1 SDK

**Comment by xybp888** [comment]
already fixed

**Comment by arichornlover** [comment]
Oh ok?

**Comment by arichornlover** [comment]
Good job on resolving it, I’m trying to figure out which header to import in my app, 16.0-newer sdks implemented something containing this “#define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))” which is new and the thing that doesn’t work with any of these below
```
// the stuff that’s used for iOS 15.5 SDK (uYouPlus)
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <dlfcn.h>
```
No one actually tells what thing you need to import so it’ll work with newer versions, it just makes code way more complicated to do.

**Comment by xybp888** [comment]
I downloaded your source code and compiled it successfully with 16.1sdk

`> Making stage for tweak uYouPlus…
> Making stage in Tweaks/Alderis…
> Making stage for xcodeproj Alderis…
> Making stage in lcpshim…
> Making stage for library libcolorpicker…
> Making stage in Tweaks/iSponsorBlock…
> Making stage for tweak iSponsorBlock…
> Making stage in Tweaks/YTUHD…
> Making stage for tweak YTUHD…
> Making stage in Tweaks/YouPiP…
> Making stage for tweak YouPiP…
> Making stage in Tweaks/Return-YouTube-Dislikes…
> Making stage for tweak YouTubeDislikesReturn…
> Making stage in Tweaks/YTABConfig…
> Making stage for tweak YTABConfig…`

**Comment by xybp888** [comment]
![8621667481098_ pic](https://user-images.githubusercontent.com/24733048/200144272-4b9e7e6b-bd2e-4a3d-9615-de54de6ba4e5.jpg)

**Comment by arichornlover** [comment]
Wait how? I tried building it with 16.x sdks and I always get this here from each app I build for it https://github.com/arichorn/uYouPlusExtra/actions/runs/3399275590/jobs/5652912849

**Comment by xybp888** [comment]
xybp888@MacBook-Pro-M1 uYouPlusExtra % make do   
> Making all for tweak uYouPlus…
==> Preprocessing Settings.xm…
==> Preprocessing Settings.xm…
==> Preprocessing uYouPlus.xm…
Use of uninitialized value $1 in split at /opt/theos/bin/logos.pl line 604.
==> Preprocessing uYouPlus.xm…
Use of uninitialized value $1 in split at /opt/theos/bin/logos.pl line 604.
==> Compiling Settings.xm (arm64e)…
==> Compiling Settings.xm (arm64)…
==> Compiling uYouPlus.xm (arm64)…
==> Compiling uYouPlus.xm (arm64e)…
==> Linking tweak uYouPlus (arm64)…
==> Generating debug symbols for uYouPlus…
==> Stripping uYouPlus (arm64)…
==> Linking tweak uYouPlus (arm64e)…
==> Generating debug symbols for uYouPlus…
==> Stripping uYouPlus (arm64e)…
==> Merging tweak uYouPlus…
==> Signing uYouPlus…
> Making all in Tweaks/Alderis…
> Making all for xcodeproj Alderis…
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-0016693E2130801E }
{ platform:macOS, arch:arm64, variant:Mac Catalyst, id:00008103-0016693E2130801E }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:00008103-0016693E2130801E }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
{ platform:iOS Simulator, id:DC970303-E4BC-4715-A1A8-C0F203F07343, OS:16.1, name:iPad (9th generation) }
{ platform:iOS Simulator, id:292E256C-7293-45ED-A995-19E2C824B281, OS:16.1, name:iPad (10th generation) }
{ platform:iOS Simulator, id:0096F282-1D6E-40BA-B49F-597F4A1FFD70, OS:16.1, name:iPad Air (5th generation) }
{ platform:iOS Simulator, id:3A932F14-5710-4756-B5F5-BBF193B1FA12, OS:16.1, name:iPad Pro (9.7-inch) }
{ platform:iOS Simulator, id:55EFF1CF-D1B1-46B8-B257-B1D42D458BFF, OS:16.1, name:iPad Pro (11-inch) (3rd generation) }
{ platform:iOS Simulator, id:0DC98BB0-A90F-44A8-93D1-3B3D400C6EFD, OS:16.1, name:iPad Pro (11-inch) (4th generation) }
{ platform:iOS Simulator, id:F1CE3B71-EDDB-4339-97AB-57DECC0CEA3F, OS:16.1, name:iPad Pro (12.9-inch) (5th generation) }
{ platform:iOS Simulator, id:6E3BD5FB-B98C-4CC5-85CF-B7A1E429E942, OS:16.1, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:707988C4-6937-41E3-9601-0945183A9886, OS:16.1, name:iPad mini (6th generation) }
{ platform:iOS Simulator, id:DF064B86-0DA1-4BCB-8A01-6FFE96B79E54, OS:16.1, name:iPhone 8 }
{ platform:iOS Simulator, id:3F23C5F8-9164-453E-9652-116C3CFA7987, OS:16.1, name:iPhone 8 Plus }
{ platform:iOS Simulator, id:E2299B61-B013-4CC4-854A-6530C6AF4164, OS:16.1, name:iPhone 11 }
{ platform:iOS Simulator, id:DF98A1AE-AF6D-4057-B990-2E5ECF44D274, OS:16.1, name:iPhone 11 Pro }
{ platform:iOS Simulator, id:6C2E3CBF-9ACD-487C-9675-22839D52E4B8, OS:16.1, name:iPhone 11 Pro Max }
{ platform:iOS Simulator, id:C87E0811-BF52-47E5-A19D-8684E90DC5A5, OS:16.1, name:iPhone 12 }
{ platform:iOS Simulator, id:C86150A5-D192-45FF-8F7E-B142F7B88E4F, OS:16.1, name:iPhone 12 Pro }
{ platform:iOS Simulator, id:01105B5F-B414-4A2B-8504-3CAC6401A2B5, OS:16.1, name:iPhone 12 Pro Max }
{ platform:iOS Simulator, id:2724FF8E-ED41-4914-865B-6C5D3EF77957, OS:16.1, name:iPhone 12 mini }
{ platform:iOS Simulator, id:B58E1868-6558-4800-A1FB-A6C60DB9129D, OS:16.1, name:iPhone 13 }
{ platform:iOS Simulator, id:2B79955F-A736-4AC4-9184-47256B755295, OS:16.1, name:iPhone 13 Pro }
{ platform:iOS Simulator, id:858B322F-1F94-436A-804F-76FC99EB0257, OS:16.1, name:iPhone 13 Pro Max }
{ platform:iOS Simulator, id:944287E8-F717-472B-8F7A-D6FF6CF5EA62, OS:16.1, name:iPhone 13 mini }
{ platform:iOS Simulator, id:C7A3332C-7058-4B7D-B406-605A7A766453, OS:16.1, name:iPhone 14 }
{ platform:iOS Simulator, id:F9FF005B-127F-42E3-9CC3-A1F5C12CC36D, OS:16.1, name:iPhone 14 Plus }
{ platform:iOS Simulator, id:E4C31D20-2A1C-4C46-A323-22BAB92CF80B, OS:16.1, name:iPhone 14 Pro }
{ platform:iOS Simulator, id:4D920B2D-7FB9-426F-8F50-32A2AF8B4362, OS:16.1, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:14AA5BC9-8F52-4CA4-9DEE-91294FA6DE85, OS:16.1, name:iPhone SE (3rd generation) }
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
note: Building targets in dependency order
warning: Run script build phase 'SwiftLint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Alderis' from project 'Alderis')
==> Signing Alderis…
> Making all in lcpshim…
==> Warning: Building for iOS 13.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for library libcolorpicker…
==> Compiling ColorFunctions.m (arm64)…
==> Compiling ColorFunctions.m (arm64e)…
==> Compiling PFColorAlert.m (arm64)…
==> Compiling PFColorCell.m (arm64)…
==> Compiling HBColorPickerTableCell.m (arm64)…
==> Compiling PFColorAlert.m (arm64e)…
==> Compiling PFLiteColorCell.m (arm64)…
==> Compiling HBColorPickerTableCell.m (arm64e)…
==> Compiling PFSimpleLiteColorCell.m (arm64)…
==> Compiling PFColorCell.m (arm64e)…
==> Compiling UIColor+PFColor.m (arm64)…
==> Compiling UIColor+PFColor.m (arm64e)…
==> Compiling PFSimpleLiteColorCell.m (arm64e)…
==> Compiling PFLiteColorCell.m (arm64e)…
==> Linking library libcolorpicker (arm64)…
ld: warning: directory not found for option '-F/Users/xybp888/Desktop/uYouPlusExtra/.theos/obj/xcode_derived/install/Library/Frameworks'
ld: warning: invalid -install_name (/Library/Frameworks/Alderis.framework/Alderis) in dependent dylib (/opt/theos/vendor/lib/Alderis.framework/Alderis.tbd). Dylibs/frameworks which might go in dyld shared cache cannot link with dylibs that won't be in the shared cache
==> Generating debug symbols for libcolorpicker…
==> Stripping libcolorpicker (arm64)…
==> Linking library libcolorpicker (arm64e)…
ld: warning: directory not found for option '-F/Users/xybp888/Desktop/uYouPlusExtra/.theos/obj/xcode_derived/install/Library/Frameworks'
ld: warning: invalid -install_name (/Library/Frameworks/Alderis.framework/Alderis) in dependent dylib (/opt/theos/vendor/lib/Alderis.framework/Alderis.tbd). Dylibs/frameworks which might go in dyld shared cache cannot link with dylibs that won't be in the shared cache
==> Generating debug symbols for libcolorpicker…
==> Stripping libcolorpicker (arm64e)…
==> Merging library libcolorpicker…
==> Signing libcolorpicker…
> Making all in Tweaks/iSponsorBlock…
==> Warning: Building for iOS 13.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak iSponsorBlock…
==> Preprocessing iSponsorBlock.xm…
==> Preprocessing iSponsorBlock.xm…
==> Compiling SponsorSegment.m (arm64e)…
==> Compiling SponsorBlockSettingsController.m (arm64e)…
==> Compiling SponsorSegmentView.m (arm64e)…
==> Compiling SponsorBlockRequest.m (arm64e)…
==> Compiling SponsorBlockRequest.m (arm64)…
==> Compiling SponsorBlockViewController.m (arm64e)…
==> Compiling MBProgressHUD.m (arm64e)…
==> Compiling SponsorSegment.m (arm64)…
==> Compiling SponsorBlockSettingsController.m (arm64)…
==> Compiling MBProgressHUD.m (arm64)…
==> Compiling SponsorSegmentView.m (arm64)…
==> Compiling SponsorBlockViewController.m (arm64)…
==> Compiling iSponsorBlock.xm (arm64e)…
==> Compiling iSponsorBlock.xm (arm64)…
==> Linking tweak iSponsorBlock (arm64e)…
==> Generating debug symbols for iSponsorBlock…
==> Stripping iSponsorBlock (arm64e)…
==> Linking tweak iSponsorBlock (arm64)…
==> Generating debug symbols for iSponsorBlock…
==> Stripping iSponsorBlock (arm64)…
==> Merging tweak iSponsorBlock…
==> Signing iSponsorBlock…
> Making all in Tweaks/YTUHD…
==> Warning: Building for iOS 11.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak YTUHD…
==> Preprocessing Tweak.x…
==> Preprocessing Tweak.x…
==> Preprocessing Settings.x…
==> Preprocessing Common.x…
==> Preprocessing Common.x…
==> Preprocessing Settings.x…
==> Compiling Tweak.x (arm64e)…
==> Compiling Tweak.x (arm64)…
==> Compiling Common.x (arm64)…
==> Compiling Common.x (arm64e)…
==> Compiling Settings.x (arm64e)…
==> Compiling Settings.x (arm64)…
==> Linking tweak YTUHD (arm64e)…
==> Generating debug symbols for YTUHD…
==> Stripping YTUHD (arm64e)…
==> Linking tweak YTUHD (arm64)…
==> Generating debug symbols for YTUHD…
==> Stripping YTUHD (arm64)…
==> Merging tweak YTUHD…
==> Signing YTUHD…
> Making all in Tweaks/YouPiP…
==> Warning: Building for iOS 11.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak YouPiP…
==> Preprocessing Settings.x…
==> Preprocessing LegacyPiPCompat.x…
==> Preprocessing Tweak.x…
==> Preprocessing Tweak.x…
==> Preprocessing Settings.x…
==> Preprocessing LegacyPiPCompat.x…
==> Compiling Settings.x (arm64)…
==> Compiling Settings.x (arm64e)…
==> Compiling LegacyPiPCompat.x (arm64)…
==> Compiling LegacyPiPCompat.x (arm64e)…
==> Compiling Tweak.x (arm64)…
==> Compiling Tweak.x (arm64e)…
==> Linking tweak YouPiP (arm64)…
==> Generating debug symbols for YouPiP…
==> Stripping YouPiP (arm64)…
==> Linking tweak YouPiP (arm64e)…
==> Generating debug symbols for YouPiP…
==> Stripping YouPiP (arm64e)…
==> Merging tweak YouPiP…
==> Signing YouPiP…
> Making all in Tweaks/Return-YouTube-Dislikes…
==> Warning: Building for iOS 11.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak YouTubeDislikesReturn…
==> Preprocessing Tweak.xm…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Compiling Tweak.xm (arm64e)…
==> Linking tweak YouTubeDislikesReturn (arm64)…
==> Generating debug symbols for YouTubeDislikesReturn…
==> Stripping YouTubeDislikesReturn (arm64)…
==> Linking tweak YouTubeDislikesReturn (arm64e)…
==> Generating debug symbols for YouTubeDislikesReturn…
==> Stripping YouTubeDislikesReturn (arm64e)…
==> Merging tweak YouTubeDislikesReturn…
==> Signing YouTubeDislikesReturn…
> Making all in Tweaks/YTABConfig…
==> Warning: Building for iOS 11.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak YTABConfig…
==> Preprocessing Tweak.xm…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Compiling Tweak.xm (arm64e)…
==> Linking tweak YTABConfig (arm64e)…
==> Generating debug symbols for YTABConfig…
==> Stripping YTABConfig (arm64e)…
==> Linking tweak YTABConfig (arm64)…
==> Generating debug symbols for YTABConfig…
==> Stripping YTABConfig (arm64)…
==> Merging tweak YTABConfig…
==> Signing YTABConfig…
> Making stage for tweak uYouPlus…
> Making stage in Tweaks/Alderis…
> Making stage for xcodeproj Alderis…
> Making stage in lcpshim…
> Making stage for library libcolorpicker…
> Making stage in Tweaks/iSponsorBlock…
> Making stage for tweak iSponsorBlock…
> Making stage in Tweaks/YTUHD…
> Making stage for tweak YTUHD…
> Making stage in Tweaks/YouPiP…
> Making stage for tweak YouPiP…
> Making stage in Tweaks/Return-YouTube-Dislikes…
> Making stage for tweak YouTubeDislikesReturn…
> Making stage in Tweaks/YTABConfig…
> Making stage for tweak YTABConfig…
==> Moving tweak's bundle to Resources/...

**Comment by arichornlover** [comment]
After seeing this I’m guessing it’s apparently possible to fix and build this without any errors on the Xcode side of things but since I don’t have a Mac all I can do is use GitHub Actions, I’m sorry if I’m wasting a lot of your time with these SDK github action errors.

**Comment by arichornlover** [comment]
https://github.com/arichorn/uYouPlusExtra/blob/main-iOS16.1_SDK/.github/workflows/buildapp.yml
also I do think this could be another reason why it broke but not efficient at coding or knowing about the problem

**Comment by xybp888** [comment]
Try to modify the system version macos-12 or macos-13

**Comment by arichornlover** [comment]
Update! I did that and it built the App successfully <— not fully true, had to remove code containing “codesign” & “install_name_tool” but made the SDK work, but the app won’t open.
https://github.com/arichorn/uYouPlusExtra/releases/tag/v17.44.4-2.1-(372)
